//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	helloeonvongithubio "github.com/eonvon/cloud-native-tour/api-aggregation-lib-multi-version/pkg/api/hello.eonvon.github.io"
	helloeonvongithubiov1 "github.com/eonvon/cloud-native-tour/api/hello.eonvon.github.io/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubiov1.FooList)(nil), (*helloeonvongithubio.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FooList_To_helloeonvongithubio_FooList(a.(*helloeonvongithubiov1.FooList), b.(*helloeonvongithubio.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubio.FooList)(nil), (*helloeonvongithubiov1.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helloeonvongithubio_FooList_To_v1_FooList(a.(*helloeonvongithubio.FooList), b.(*helloeonvongithubiov1.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*helloeonvongithubio.FooSpec)(nil), (*helloeonvongithubiov1.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helloeonvongithubio_FooSpec_To_v1_FooSpec(a.(*helloeonvongithubio.FooSpec), b.(*helloeonvongithubiov1.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*helloeonvongithubio.Foo)(nil), (*helloeonvongithubiov1.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helloeonvongithubio_Foo_To_v1_Foo(a.(*helloeonvongithubio.Foo), b.(*helloeonvongithubiov1.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*helloeonvongithubiov1.FooSpec)(nil), (*helloeonvongithubio.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FooSpec_To_helloeonvongithubio_FooSpec(a.(*helloeonvongithubiov1.FooSpec), b.(*helloeonvongithubio.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*helloeonvongithubiov1.Foo)(nil), (*helloeonvongithubio.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Foo_To_helloeonvongithubio_Foo(a.(*helloeonvongithubiov1.Foo), b.(*helloeonvongithubio.Foo), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Foo_To_helloeonvongithubio_Foo(in *helloeonvongithubiov1.Foo, out *helloeonvongithubio.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_FooSpec_To_helloeonvongithubio_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_helloeonvongithubio_Foo_To_v1_Foo(in *helloeonvongithubio.Foo, out *helloeonvongithubiov1.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_helloeonvongithubio_FooSpec_To_v1_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	// WARNING: in.Status requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1_FooList_To_helloeonvongithubio_FooList(in *helloeonvongithubiov1.FooList, out *helloeonvongithubio.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]helloeonvongithubio.Foo, len(*in))
		for i := range *in {
			if err := Convert_v1_Foo_To_helloeonvongithubio_Foo(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1_FooList_To_helloeonvongithubio_FooList is an autogenerated conversion function.
func Convert_v1_FooList_To_helloeonvongithubio_FooList(in *helloeonvongithubiov1.FooList, out *helloeonvongithubio.FooList, s conversion.Scope) error {
	return autoConvert_v1_FooList_To_helloeonvongithubio_FooList(in, out, s)
}

func autoConvert_helloeonvongithubio_FooList_To_v1_FooList(in *helloeonvongithubio.FooList, out *helloeonvongithubiov1.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]helloeonvongithubiov1.Foo, len(*in))
		for i := range *in {
			if err := Convert_helloeonvongithubio_Foo_To_v1_Foo(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_helloeonvongithubio_FooList_To_v1_FooList is an autogenerated conversion function.
func Convert_helloeonvongithubio_FooList_To_v1_FooList(in *helloeonvongithubio.FooList, out *helloeonvongithubiov1.FooList, s conversion.Scope) error {
	return autoConvert_helloeonvongithubio_FooList_To_v1_FooList(in, out, s)
}

func autoConvert_v1_FooSpec_To_helloeonvongithubio_FooSpec(in *helloeonvongithubiov1.FooSpec, out *helloeonvongithubio.FooSpec, s conversion.Scope) error {
	// WARNING: in.Msg requires manual conversion: does not exist in peer-type
	// WARNING: in.Description requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_helloeonvongithubio_FooSpec_To_v1_FooSpec(in *helloeonvongithubio.FooSpec, out *helloeonvongithubiov1.FooSpec, s conversion.Scope) error {
	// WARNING: in.Image requires manual conversion: does not exist in peer-type
	// WARNING: in.Config requires manual conversion: does not exist in peer-type
	return nil
}
