//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v2

import (
	unsafe "unsafe"

	greeting "github.com/foenye/cloud-native-tour/crd-getting-started/pkg/apis/greeting"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Foo)(nil), (*greeting.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Foo_To_greeting_Foo(a.(*Foo), b.(*greeting.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*greeting.Foo)(nil), (*Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_greeting_Foo_To_v2_Foo(a.(*greeting.Foo), b.(*Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooCondition)(nil), (*greeting.FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooCondition_To_greeting_FooCondition(a.(*FooCondition), b.(*greeting.FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*greeting.FooCondition)(nil), (*FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_greeting_FooCondition_To_v2_FooCondition(a.(*greeting.FooCondition), b.(*FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooConfig)(nil), (*greeting.FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooConfig_To_greeting_FooConfig(a.(*FooConfig), b.(*greeting.FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*greeting.FooConfig)(nil), (*FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_greeting_FooConfig_To_v2_FooConfig(a.(*greeting.FooConfig), b.(*FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooList)(nil), (*greeting.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooList_To_greeting_FooList(a.(*FooList), b.(*greeting.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*greeting.FooList)(nil), (*FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_greeting_FooList_To_v2_FooList(a.(*greeting.FooList), b.(*FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooSpec)(nil), (*greeting.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooSpec_To_greeting_FooSpec(a.(*FooSpec), b.(*greeting.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*greeting.FooSpec)(nil), (*FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_greeting_FooSpec_To_v2_FooSpec(a.(*greeting.FooSpec), b.(*FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooStatus)(nil), (*greeting.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooStatus_To_greeting_FooStatus(a.(*FooStatus), b.(*greeting.FooStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*greeting.FooStatus)(nil), (*FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_greeting_FooStatus_To_v2_FooStatus(a.(*greeting.FooStatus), b.(*FooStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v2_Foo_To_greeting_Foo(in *Foo, out *greeting.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_FooSpec_To_greeting_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v2_FooStatus_To_greeting_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_Foo_To_greeting_Foo is an autogenerated conversion function.
func Convert_v2_Foo_To_greeting_Foo(in *Foo, out *greeting.Foo, s conversion.Scope) error {
	return autoConvert_v2_Foo_To_greeting_Foo(in, out, s)
}

func autoConvert_greeting_Foo_To_v2_Foo(in *greeting.Foo, out *Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_greeting_FooSpec_To_v2_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_greeting_FooStatus_To_v2_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_greeting_Foo_To_v2_Foo is an autogenerated conversion function.
func Convert_greeting_Foo_To_v2_Foo(in *greeting.Foo, out *Foo, s conversion.Scope) error {
	return autoConvert_greeting_Foo_To_v2_Foo(in, out, s)
}

func autoConvert_v2_FooCondition_To_greeting_FooCondition(in *FooCondition, out *greeting.FooCondition, s conversion.Scope) error {
	out.Type = greeting.FooConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	return nil
}

// Convert_v2_FooCondition_To_greeting_FooCondition is an autogenerated conversion function.
func Convert_v2_FooCondition_To_greeting_FooCondition(in *FooCondition, out *greeting.FooCondition, s conversion.Scope) error {
	return autoConvert_v2_FooCondition_To_greeting_FooCondition(in, out, s)
}

func autoConvert_greeting_FooCondition_To_v2_FooCondition(in *greeting.FooCondition, out *FooCondition, s conversion.Scope) error {
	out.Type = FooConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	return nil
}

// Convert_greeting_FooCondition_To_v2_FooCondition is an autogenerated conversion function.
func Convert_greeting_FooCondition_To_v2_FooCondition(in *greeting.FooCondition, out *FooCondition, s conversion.Scope) error {
	return autoConvert_greeting_FooCondition_To_v2_FooCondition(in, out, s)
}

func autoConvert_v2_FooConfig_To_greeting_FooConfig(in *FooConfig, out *greeting.FooConfig, s conversion.Scope) error {
	out.Message = in.Message
	out.Description = in.Description
	return nil
}

// Convert_v2_FooConfig_To_greeting_FooConfig is an autogenerated conversion function.
func Convert_v2_FooConfig_To_greeting_FooConfig(in *FooConfig, out *greeting.FooConfig, s conversion.Scope) error {
	return autoConvert_v2_FooConfig_To_greeting_FooConfig(in, out, s)
}

func autoConvert_greeting_FooConfig_To_v2_FooConfig(in *greeting.FooConfig, out *FooConfig, s conversion.Scope) error {
	out.Message = in.Message
	out.Description = in.Description
	return nil
}

// Convert_greeting_FooConfig_To_v2_FooConfig is an autogenerated conversion function.
func Convert_greeting_FooConfig_To_v2_FooConfig(in *greeting.FooConfig, out *FooConfig, s conversion.Scope) error {
	return autoConvert_greeting_FooConfig_To_v2_FooConfig(in, out, s)
}

func autoConvert_v2_FooList_To_greeting_FooList(in *FooList, out *greeting.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]greeting.Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v2_FooList_To_greeting_FooList is an autogenerated conversion function.
func Convert_v2_FooList_To_greeting_FooList(in *FooList, out *greeting.FooList, s conversion.Scope) error {
	return autoConvert_v2_FooList_To_greeting_FooList(in, out, s)
}

func autoConvert_greeting_FooList_To_v2_FooList(in *greeting.FooList, out *FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_greeting_FooList_To_v2_FooList is an autogenerated conversion function.
func Convert_greeting_FooList_To_v2_FooList(in *greeting.FooList, out *FooList, s conversion.Scope) error {
	return autoConvert_greeting_FooList_To_v2_FooList(in, out, s)
}

func autoConvert_v2_FooSpec_To_greeting_FooSpec(in *FooSpec, out *greeting.FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_v2_FooConfig_To_greeting_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_FooSpec_To_greeting_FooSpec is an autogenerated conversion function.
func Convert_v2_FooSpec_To_greeting_FooSpec(in *FooSpec, out *greeting.FooSpec, s conversion.Scope) error {
	return autoConvert_v2_FooSpec_To_greeting_FooSpec(in, out, s)
}

func autoConvert_greeting_FooSpec_To_v2_FooSpec(in *greeting.FooSpec, out *FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_greeting_FooConfig_To_v2_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_greeting_FooSpec_To_v2_FooSpec is an autogenerated conversion function.
func Convert_greeting_FooSpec_To_v2_FooSpec(in *greeting.FooSpec, out *FooSpec, s conversion.Scope) error {
	return autoConvert_greeting_FooSpec_To_v2_FooSpec(in, out, s)
}

func autoConvert_v2_FooStatus_To_greeting_FooStatus(in *FooStatus, out *greeting.FooStatus, s conversion.Scope) error {
	out.Phase = greeting.FooPhase(in.Phase)
	out.Conditions = *(*[]greeting.FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v2_FooStatus_To_greeting_FooStatus is an autogenerated conversion function.
func Convert_v2_FooStatus_To_greeting_FooStatus(in *FooStatus, out *greeting.FooStatus, s conversion.Scope) error {
	return autoConvert_v2_FooStatus_To_greeting_FooStatus(in, out, s)
}

func autoConvert_greeting_FooStatus_To_v2_FooStatus(in *greeting.FooStatus, out *FooStatus, s conversion.Scope) error {
	out.Phase = FooPhase(in.Phase)
	out.Conditions = *(*[]FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_greeting_FooStatus_To_v2_FooStatus is an autogenerated conversion function.
func Convert_greeting_FooStatus_To_v2_FooStatus(in *greeting.FooStatus, out *FooStatus, s conversion.Scope) error {
	return autoConvert_greeting_FooStatus_To_v2_FooStatus(in, out, s)
}
