POST localhost:8000/apis/apps/v1/namespaces/default/deployments
Content-Type: application/yaml

< ./nginx-deploy.yaml
###
GET localhost:8000/apis/apps/v1/namespaces/default/deployments
Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
###
DELETE localhost:8000/apis/apps/v1/namespaces/default/deployments/nginx-deploy
Content-Type: application/yaml

gracePeriodSeconds: 0
orphanDependents: false