//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v2

import (
	unsafe "unsafe"

	helloeonvongithubio "github.com/eonvon/cloud-native-tour/api-aggregation-lib-multi-version/pkg/api/hello.eonvon.github.io"
	helloeonvongithubiov2 "github.com/eonvon/cloud-native-tour/api/hello.eonvon.github.io/v2"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubiov2.Foo)(nil), (*helloeonvongithubio.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Foo_To_helloeonvongithubio_Foo(a.(*helloeonvongithubiov2.Foo), b.(*helloeonvongithubio.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubio.Foo)(nil), (*helloeonvongithubiov2.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helloeonvongithubio_Foo_To_v2_Foo(a.(*helloeonvongithubio.Foo), b.(*helloeonvongithubiov2.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubiov2.FooCondition)(nil), (*helloeonvongithubio.FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooCondition_To_helloeonvongithubio_FooCondition(a.(*helloeonvongithubiov2.FooCondition), b.(*helloeonvongithubio.FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubio.FooCondition)(nil), (*helloeonvongithubiov2.FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helloeonvongithubio_FooCondition_To_v2_FooCondition(a.(*helloeonvongithubio.FooCondition), b.(*helloeonvongithubiov2.FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubiov2.FooConfig)(nil), (*helloeonvongithubio.FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooConfig_To_helloeonvongithubio_FooConfig(a.(*helloeonvongithubiov2.FooConfig), b.(*helloeonvongithubio.FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubio.FooConfig)(nil), (*helloeonvongithubiov2.FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helloeonvongithubio_FooConfig_To_v2_FooConfig(a.(*helloeonvongithubio.FooConfig), b.(*helloeonvongithubiov2.FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubiov2.FooList)(nil), (*helloeonvongithubio.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooList_To_helloeonvongithubio_FooList(a.(*helloeonvongithubiov2.FooList), b.(*helloeonvongithubio.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubio.FooList)(nil), (*helloeonvongithubiov2.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helloeonvongithubio_FooList_To_v2_FooList(a.(*helloeonvongithubio.FooList), b.(*helloeonvongithubiov2.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubiov2.FooSpec)(nil), (*helloeonvongithubio.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooSpec_To_helloeonvongithubio_FooSpec(a.(*helloeonvongithubiov2.FooSpec), b.(*helloeonvongithubio.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubio.FooSpec)(nil), (*helloeonvongithubiov2.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helloeonvongithubio_FooSpec_To_v2_FooSpec(a.(*helloeonvongithubio.FooSpec), b.(*helloeonvongithubiov2.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubiov2.FooStatus)(nil), (*helloeonvongithubio.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooStatus_To_helloeonvongithubio_FooStatus(a.(*helloeonvongithubiov2.FooStatus), b.(*helloeonvongithubio.FooStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helloeonvongithubio.FooStatus)(nil), (*helloeonvongithubiov2.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helloeonvongithubio_FooStatus_To_v2_FooStatus(a.(*helloeonvongithubio.FooStatus), b.(*helloeonvongithubiov2.FooStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v2_Foo_To_helloeonvongithubio_Foo(in *helloeonvongithubiov2.Foo, out *helloeonvongithubio.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_FooSpec_To_helloeonvongithubio_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v2_FooStatus_To_helloeonvongithubio_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_Foo_To_helloeonvongithubio_Foo is an autogenerated conversion function.
func Convert_v2_Foo_To_helloeonvongithubio_Foo(in *helloeonvongithubiov2.Foo, out *helloeonvongithubio.Foo, s conversion.Scope) error {
	return autoConvert_v2_Foo_To_helloeonvongithubio_Foo(in, out, s)
}

func autoConvert_helloeonvongithubio_Foo_To_v2_Foo(in *helloeonvongithubio.Foo, out *helloeonvongithubiov2.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_helloeonvongithubio_FooSpec_To_v2_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_helloeonvongithubio_FooStatus_To_v2_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_helloeonvongithubio_Foo_To_v2_Foo is an autogenerated conversion function.
func Convert_helloeonvongithubio_Foo_To_v2_Foo(in *helloeonvongithubio.Foo, out *helloeonvongithubiov2.Foo, s conversion.Scope) error {
	return autoConvert_helloeonvongithubio_Foo_To_v2_Foo(in, out, s)
}

func autoConvert_v2_FooCondition_To_helloeonvongithubio_FooCondition(in *helloeonvongithubiov2.FooCondition, out *helloeonvongithubio.FooCondition, s conversion.Scope) error {
	out.Type = helloeonvongithubio.FooConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	return nil
}

// Convert_v2_FooCondition_To_helloeonvongithubio_FooCondition is an autogenerated conversion function.
func Convert_v2_FooCondition_To_helloeonvongithubio_FooCondition(in *helloeonvongithubiov2.FooCondition, out *helloeonvongithubio.FooCondition, s conversion.Scope) error {
	return autoConvert_v2_FooCondition_To_helloeonvongithubio_FooCondition(in, out, s)
}

func autoConvert_helloeonvongithubio_FooCondition_To_v2_FooCondition(in *helloeonvongithubio.FooCondition, out *helloeonvongithubiov2.FooCondition, s conversion.Scope) error {
	out.Type = helloeonvongithubiov2.FooConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	return nil
}

// Convert_helloeonvongithubio_FooCondition_To_v2_FooCondition is an autogenerated conversion function.
func Convert_helloeonvongithubio_FooCondition_To_v2_FooCondition(in *helloeonvongithubio.FooCondition, out *helloeonvongithubiov2.FooCondition, s conversion.Scope) error {
	return autoConvert_helloeonvongithubio_FooCondition_To_v2_FooCondition(in, out, s)
}

func autoConvert_v2_FooConfig_To_helloeonvongithubio_FooConfig(in *helloeonvongithubiov2.FooConfig, out *helloeonvongithubio.FooConfig, s conversion.Scope) error {
	out.Msg = in.Msg
	out.Description = in.Description
	return nil
}

// Convert_v2_FooConfig_To_helloeonvongithubio_FooConfig is an autogenerated conversion function.
func Convert_v2_FooConfig_To_helloeonvongithubio_FooConfig(in *helloeonvongithubiov2.FooConfig, out *helloeonvongithubio.FooConfig, s conversion.Scope) error {
	return autoConvert_v2_FooConfig_To_helloeonvongithubio_FooConfig(in, out, s)
}

func autoConvert_helloeonvongithubio_FooConfig_To_v2_FooConfig(in *helloeonvongithubio.FooConfig, out *helloeonvongithubiov2.FooConfig, s conversion.Scope) error {
	out.Msg = in.Msg
	out.Description = in.Description
	return nil
}

// Convert_helloeonvongithubio_FooConfig_To_v2_FooConfig is an autogenerated conversion function.
func Convert_helloeonvongithubio_FooConfig_To_v2_FooConfig(in *helloeonvongithubio.FooConfig, out *helloeonvongithubiov2.FooConfig, s conversion.Scope) error {
	return autoConvert_helloeonvongithubio_FooConfig_To_v2_FooConfig(in, out, s)
}

func autoConvert_v2_FooList_To_helloeonvongithubio_FooList(in *helloeonvongithubiov2.FooList, out *helloeonvongithubio.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]helloeonvongithubio.Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v2_FooList_To_helloeonvongithubio_FooList is an autogenerated conversion function.
func Convert_v2_FooList_To_helloeonvongithubio_FooList(in *helloeonvongithubiov2.FooList, out *helloeonvongithubio.FooList, s conversion.Scope) error {
	return autoConvert_v2_FooList_To_helloeonvongithubio_FooList(in, out, s)
}

func autoConvert_helloeonvongithubio_FooList_To_v2_FooList(in *helloeonvongithubio.FooList, out *helloeonvongithubiov2.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]helloeonvongithubiov2.Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_helloeonvongithubio_FooList_To_v2_FooList is an autogenerated conversion function.
func Convert_helloeonvongithubio_FooList_To_v2_FooList(in *helloeonvongithubio.FooList, out *helloeonvongithubiov2.FooList, s conversion.Scope) error {
	return autoConvert_helloeonvongithubio_FooList_To_v2_FooList(in, out, s)
}

func autoConvert_v2_FooSpec_To_helloeonvongithubio_FooSpec(in *helloeonvongithubiov2.FooSpec, out *helloeonvongithubio.FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_v2_FooConfig_To_helloeonvongithubio_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_FooSpec_To_helloeonvongithubio_FooSpec is an autogenerated conversion function.
func Convert_v2_FooSpec_To_helloeonvongithubio_FooSpec(in *helloeonvongithubiov2.FooSpec, out *helloeonvongithubio.FooSpec, s conversion.Scope) error {
	return autoConvert_v2_FooSpec_To_helloeonvongithubio_FooSpec(in, out, s)
}

func autoConvert_helloeonvongithubio_FooSpec_To_v2_FooSpec(in *helloeonvongithubio.FooSpec, out *helloeonvongithubiov2.FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_helloeonvongithubio_FooConfig_To_v2_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_helloeonvongithubio_FooSpec_To_v2_FooSpec is an autogenerated conversion function.
func Convert_helloeonvongithubio_FooSpec_To_v2_FooSpec(in *helloeonvongithubio.FooSpec, out *helloeonvongithubiov2.FooSpec, s conversion.Scope) error {
	return autoConvert_helloeonvongithubio_FooSpec_To_v2_FooSpec(in, out, s)
}

func autoConvert_v2_FooStatus_To_helloeonvongithubio_FooStatus(in *helloeonvongithubiov2.FooStatus, out *helloeonvongithubio.FooStatus, s conversion.Scope) error {
	out.Phase = helloeonvongithubio.FooPhase(in.Phase)
	out.Conditions = *(*[]helloeonvongithubio.FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v2_FooStatus_To_helloeonvongithubio_FooStatus is an autogenerated conversion function.
func Convert_v2_FooStatus_To_helloeonvongithubio_FooStatus(in *helloeonvongithubiov2.FooStatus, out *helloeonvongithubio.FooStatus, s conversion.Scope) error {
	return autoConvert_v2_FooStatus_To_helloeonvongithubio_FooStatus(in, out, s)
}

func autoConvert_helloeonvongithubio_FooStatus_To_v2_FooStatus(in *helloeonvongithubio.FooStatus, out *helloeonvongithubiov2.FooStatus, s conversion.Scope) error {
	out.Phase = helloeonvongithubiov2.FooPhase(in.Phase)
	out.Conditions = *(*[]helloeonvongithubiov2.FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_helloeonvongithubio_FooStatus_To_v2_FooStatus is an autogenerated conversion function.
func Convert_helloeonvongithubio_FooStatus_To_v2_FooStatus(in *helloeonvongithubio.FooStatus, out *helloeonvongithubiov2.FooStatus, s conversion.Scope) error {
	return autoConvert_helloeonvongithubio_FooStatus_To_v2_FooStatus(in, out, s)
}
