// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/foenye/cloud-native-tour/crd-getting-started/pkg/client/clientset_generated/clientset/typed/greeting/v2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeGreetingV2 struct {
	*testing.Fake
}

func (c *FakeGreetingV2) Foos(namespace string) v2.FooInterface {
	return newFakeFoos(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeGreetingV2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
