// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/foenye/cloud-native-tour/crd-getting-started/pkg/apis/greeting/v2"
	greetingv2 "github.com/foenye/cloud-native-tour/crd-getting-started/pkg/client/clientset_generated/clientset/typed/greeting/v2"
	gentype "k8s.io/client-go/gentype"
)

// fakeFoos implements FooInterface
type fakeFoos struct {
	*gentype.FakeClientWithList[*v2.Foo, *v2.FooList]
	Fake *FakeGreetingV2
}

func newFakeFoos(fake *FakeGreetingV2, namespace string) greetingv2.FooInterface {
	return &fakeFoos{
		gentype.NewFakeClientWithList[*v2.Foo, *v2.FooList](
			fake.Fake,
			namespace,
			v2.SchemeGroupVersion.WithResource("foos"),
			v2.SchemeGroupVersion.WithKind("Foo"),
			func() *v2.Foo { return &v2.Foo{} },
			func() *v2.FooList { return &v2.FooList{} },
			func(dst, src *v2.FooList) { dst.ListMeta = src.ListMeta },
			func(list *v2.FooList) []*v2.Foo { return gentype.ToPointerSlice(list.Items) },
			func(list *v2.FooList, items []*v2.Foo) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
