#!/usr/bin/env bash

# Usage:
#     helpers "${APIROOT}"
#     An example APIROOT is: "pkg/apis"

set -o errexit
set -o nounset
set -o pipefail

PROJECT_MOD="${PROJECT_MOD:-""}"
[ -z "${PROJECT_MOD}" ] && echo "PROJECT_MOD env var is required" && exit 1

BOILERPLATE_CUSTOM=/tmp/custom-boilerplate.txt
[[ -f ${BOILERPLATE_CUSTOM} ]] || touch ${BOILERPLATE_CUSTOM}

source "$GOPATH/src/k8s.io/code-generator/kube_codegen.sh"

THIS_PKG="${PROJECT_MOD}"
cd ${GOPATH}/src/${PROJECT_MOD}

kube::codegen::gen_client \
    --with-watch \
    --output-dir "pkg/client" \
    --output-pkg "${THIS_PKG}/pkg/client" \
    --clientset-name "clientset_generated" \
    --versioned-name "clientset" \
    --boilerplate "${BOILERPLATE_CUSTOM}" \
    --prefers-protobuf \
    "${*}"